=== GossJS/15092017-studyminbulat/part3/task3.dtd
<?xml version="1.0" encoding="utf-8" ?>
        <!ELEMENT visits (most-popular-ip, desktop, mobile, popular-ips)>
        <!ELEMENT most-popular-ip (#PCDATA)>
        <!ELEMENT desktop (platform*)>
        <!ELEMENT mobile (platform*)>
        <!ELEMENT popular-ips (ip*)>
        <!ELEMENT platform (#PCDATA)>
        <!ELEMENT ip EMPTY>
        <!ATTLIST platform name CDATA #REQUIRED>
        <!ATTLIST ip addr CDATA #REQUIRED>
        <!ATTLIST ip frequency CDATA #REQUIRED>

=== GossJS/15092017-studyminbulat/part3/task3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE visits PUBLIC "Bulat" "task3.dtd">
<visits>
    <most-popular-ip>077.234.203.101</most-popular-ip>
    <desktop>
        <platform name="Windows">87</platform>
        <platform name="Linux">18</platform>
        <platform name="MacOS">6</platform>
    </desktop>
    <mobile>
        <platform name="iPhone">5</platform>
        <platform name="Android">10</platform>
    </mobile>
    <popular-ips>
        <ip addr="077.234.203.101" frequency="12"/>
        <ip addr="005.144.096.251" frequency="11"/>
        <ip addr="081.222.086.058" frequency="6"/>
        <ip addr="005.164.066.173" frequency="4"/>
        <ip addr="094.019.018.060" frequency="4"/>
    </popular-ips>
</visits>
